/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package json;

import java.io.File;

public class App {

  /**
   * @param fileNameSave
   * @param keyCheckJson
   * @param folderFileJson
   * @param isFileInResource
   */
  public static void main(String[] args) {
    if(args.length != 4) {
      System.out.println("param number is not correct");
      return;
    }
    String fileName = args[0];
    String keyCheck = args[1];
    String folderFileJson = args[2];
    Boolean isFolerInResource = Boolean.valueOf(args[3]);
    FileJsonResource fileJsonResource = new FileJsonResource(folderFileJson, isFolerInResource);
    File fileSave = new File(fileName);

    if (fileSave.exists()) {
      fileSave.delete();
    }

    fileJsonResource
        .getValueFromKey(keyCheck)
        .forEach(
            (key, value) -> {
              fileJsonResource.writeValueToFile(fileName, key, value);
            });
  }
}
