/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package json;

import java.io.File;

public class App {

  /**
   * @param fileNameSave
   * @param keyCheckJson
   * @param folderFileJson
   * @param isFileInResource
   */
  public static void main(String[] args) {
    String fileName;
    String keyCheck;
    String folderFileJson;
    Boolean isFolerInResource;

    if (args.length == 4) {
      System.out.println("param number is not correct");
      fileName = args[0];
      keyCheck = args[1];
      folderFileJson = args[2];
      isFolerInResource = Boolean.valueOf(args[3]);
    } else {
      fileName = "check.txt";
      keyCheck = "text";
      folderFileJson = "filejson";
      isFolerInResource = false;
    }

    FileJsonResource fileJsonResource = new FileJsonResource(folderFileJson, isFolerInResource);
    File fileSave = new File(fileName);

    if (fileSave.exists()) {
      fileSave.delete();
    }

    fileJsonResource
        .getValueFromKey(keyCheck)
        .forEach(
            (key, value) -> {
              fileJsonResource.writeValueToFile(fileName, key, value);
            });
  }
}
